---

- name: Add Docker GPG key
  apt_key:
    url: "{{docker_gpg_url}}"
    state: present

- name: Install Docker
  apt: name={{docker_packges}} state=latest update_cache=yes

- name: Install Python Docker module
  pip:
    name: docker

- name: Add adminstrator to docker group
  user:
    name: "{{admin_user}}"
    groups: docker
    append: yes

- name: Install Docker Compose
  get_url:
    url: "{{docker_compose_url}}"
    dest: /usr/local/bin/docker-compose
    mode: u+x,g+x,o+x
